# Generated by Django 5.0.2 on 2025-06-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIToken',
        ),
    ]
